export const FETCH_ROOM_MEMBERS = "FETCH_ROOM_MEMBERS";
export const FETCH_ROOM_MEMBERS_SUCCESS = "FETCH_ROOM_MEMBERS_SUCCESS";
export const FETCH_ROOM_MEMBERS_FAILURE = "FETCH_ROOM_MEMBERS_FAILURE";

