export const FETCH_ROOM_CONVERSATION = "FETCH_ROOM_CONVERSATION";
export const FETCH_ROOM_CONVERSATION_SUCCESS = "FETCH_ROOM_CONVERSATION_SUCCESS";
export const FETCH_ROOM_CONVERSATION_FAILURE = "FETCH_ROOM_CONVERSATION_FAILURE";
export const ADD_MEMBER_TO_ROOM = "ADD_MEMBER_TO_ROOM";
export const ADD_ADMIN_TO_ROOM = "ADD_ADMIN_TO_ROOM";

