export const FETCH_ROOM_CONVERSATION = "FETCH_ROOM_CONVERSATION";
export const FETCH_ROOM_CONVERSATION_SUCCESS = "FETCH_ROOM_CONVERSATION_SUCCESS";
export const FETCH_ROOM_CONVERSATION_FAILURE = "FETCH_ROOM_CONVERSATION_FAILURE";
