export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_REQUEST_SUCCESS = "ADD_USER_REQUEST_SUCCESS";
export const ADD_USER_REQUEST_FAILURE = "ADD_USER_REQUEST_FAILURE";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const TOGGLE_USER_LOGIN_DIALOG = "TOGGLE_USER_LOGIN_DIALOG";


