export const CREATE_ROOM = "CREATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
export const FETCH_ROOMS_REQUEST = "FETCH_ROOMS_REQUEST";
export const FETCH_ROOMS_REQUEST_SUCCESS = "FETCH_ROOMS_REQUEST_SUCCESS";
export const FETCH_ROOMS_REQUEST_FAILURE = "FETCH_ROOMS_REQUEST_FAILURE";
