export const CREATE_ROOM_REQUEST = "CREATE_ROOM_REQUEST";
export const CREATE_ROOM_REQUEST_SUCCESS = "CREATE_ROOM_REQUEST_SUCCESS";
export const CREATE_ROOM_REQUEST_FAILURE = "CREATE_ROOM_REQUEST_FAILURE";

export const TOGGLE_CREATE_ROOM_DIALOG = "TOGGLE_CREATE_ROOM_DIALOG";
export const DELETE_ROOM = "DELETE_ROOM";
export const CLOSE_ROOM = "CLOSE_ROOM";
export const ADD_ROOM_TO_FAVOURITES = "ADD_ROOM_TO_FAVOURITES";

export const FETCH_ROOMS_REQUEST = "FETCH_ROOMS_REQUEST";
export const FETCH_ROOMS_REQUEST_SUCCESS = "FETCH_ROOMS_REQUEST_SUCCESS";
export const FETCH_ROOMS_REQUEST_FAILURE = "FETCH_ROOMS_REQUEST_FAILURE";

export const SELECT_ROOM_REQUEST = "SELECT_ROOM_REQUEST";
export const SELECT_ROOM_REQUEST_SUCCESS = "SELECT_ROOM_REQUEST_SUCCESS";
export const SELECT_ROOM_REQUEST_FAILURE = "SELECT_ROOM_REQUEST_FAILURE";

export const ADD_MEMBER_TO_ROOM_REQUEST = "ADD_MEMBER_TO_ROOM_REQUEST";
export const ADD_MEMBER_TO_ROOM_REQUEST_SUCCESS = "ADD_MEMBER_TO_ROOM_REQUEST_SUCCESS";
export const ADD_MEMBER_TO_ROOM_REQUEST_FAILURE = "ADD_MEMBER_TO_ROOM_REQUEST_FAILURE";

export const ADD_ADMIN_TO_ROOM_REQUEST = "ADD_ADMIN_TO_ROOM_REQUEST";
export const ADD_ADMIN_TO_ROOM_REQUEST_SUCCESS = "ADD_ADMIN_TO_ROOM_REQUEST_SUCCESS";
export const ADD_ADMIN_TO_ROOM_REQUEST_FAILURE = "ADD_ADMIN_TO_ROOM_REQUEST_FAILURE";

export const FETCH_ROOM_CONVERSATION_REQUEST = "FETCH_ROOM_CONVERSATION_REQUEST";
export const FETCH_ROOM_CONVERSATION_REQUEST_SUCCESS = "FETCH_ROOM_CONVERSATION_REQUEST_SUCCESS";
export const FETCH_ROOM_CONVERSATION_REQUEST_FAILURE = "FETCH_ROOM_CONVERSATION_REQUEST_FAILURE";

export const CREATE_CHAT_MESSAGE_REQUEST = "CREATE_CHAT_MESSAGE_REQUEST"
export const CREATE_CHAT_MESSAGE_REQUEST_SUCCESS = "CREATE_CHAT_MESSAGE_REQUEST_SUCCESS"
export const CREATE_CHAT_MESSAGE_REQUEST_FAILURE = "CREATE_CHAT_MESSAGE_REQUEST_FAILURE"
